name: tengo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_resizable_container: ^3.0.0
  equatable: ^2.0.5
  figma_squircle: ^0.5.3
  bloc: ^8.1.4
  flutter_build_debian: ^0.0.1
  extended_text_field: ^16.0.0
  cardoteka: ^1.1.0
  # desktop_multi_window: ^0.2.0
  # window_manager_plus: 
  # bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
